Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from selenium import webdriver
... from selenium.webdriver.common.by import By
... 
... driver = webdriver.Firefox()
... # maximize browser
... driver.maximize_window()
... driver.get("http://www.theTestingWorld.com/testings")
... 
... # enter data to the textbox
... 
... driver.find_element(By.NAME, "fld_username").send_keys("himanshu")
... 
... driver.find_element(By.NAME, "fld_email").send_keys("himanshu@1234")
... 
... driver.find_element(By.NAME, "fld_password").send_keys("12345678")
... 
... driver.find_element(By.NAME,"fld_cpassword").send_keys("12345678")
... 
... driver.find_element(By.NAME,"dob").send_keys("14.10.2000")
... 
... driver.find_element(By.NAME,"phone").send_keys("1234567890")
... 
... driver.find_element(By.NAME,"address").send_keys("244 ave san deigo")
... 
... # working on radio button
... 
... driver.find_element(By.XPATH,"/html/body/div[4]/section/ul/li[1]/div/form/input[9]").click()
... 
... driver.find_element(By.XPATH,"/html/body/div[4]/section/ul/li[1]/div/form/div/input[2]").click()
